branches:
  only:
    - master

language: php


install: sh -c ' cd pulse2 && sh autogen.sh && ./configure && make'

notifications:
  email:
    recipients:
      - nicolas.lecureuil@siveo.net
    on_success: change
    on_failure: always
