branches:
  only:
    - master
  
before_install:
    cd pulse

install: sh autogen.sh && ./configure && make

notifications:
  email:
    recipients:
      - nicolas.lecureuil@siveo.net
    on_success: change
    on_failure: always
