branches:
  only:
    - master

language: php

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y python-sqlalchemy python-mysqldb python-twisted-web

install: sh -c ' cd pulse2 && sh autogen.sh && ./configure && make'

notifications:
  email:
    recipients:
      - nicolas.lecureuil@siveo.net
    on_success: change
    on_failure: always
